config/routes.rb
Blogin15::Application.routes.draw do |map|
  resources :posts do
	resources :comments
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments

	validates_presence_of :title
	validates_presence_of :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_filter do
		@post = Post.find_by_id(params[:post_id])
	end	
	
	def create		
		@post.comments.create(params[:comment])
		redirect_to @post
	end
	
	def destroy		
		comment = Comment.find_by_id(params[:id])
		comment.destroy
		redirect_to @post
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	respond_to :html, :atom
	
	def index
		@posts = Post.order("created_at desc")
		respond_with @posts
	end
	
	def show
		@post = Post.find_by_id(params[:id])
		respond_with @post
	end
	
	def new
		@post = Post.new
	end
	
	def create
		@post = Post.new(params[:post])
		if @post.save
			redirect_to posts_path
		else
			render "new"
		end
		
	end	
	
	def edit
		@post = Post.find_by_id(params[:id])
	end
	
	def update
		@post = Post.find_by_id(params[:id])
		
		if @post.update_attributes(params[:post])
			redirect_to posts_path
		else
			render "edit"
		end	
	end
	
	def destroy
		post = Post.find_by_id(params[:id])
		post.destroy
		redirect_to posts_path, :notice => "#{post.title} was deleted"
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title><%= controller_name.humanize %>: <%= action_name %></title>
	<%= stylesheet_link_tag 'application' %>
	<%= javascript_include_tag :defaults %>
	<%= csrf_meta_tag %>
	<%= auto_discovery_link_tag(:atom, posts_path(:atom))%>
</head>
<body>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |form| %>
	<%= form.error_messages %>
	
	<%= form.text_field :title %>
	<%= form.text_area :body %>
	<%= form.submit %>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit a post</h1>
<%= render "form" %>

app/views/posts/index.html.erb
<h1>My Blog!</h1>
<% @posts.each do |post| %>
<h2><%= link_to post.title, post %></h2>
<div class="entry">	
	<%= link_to "Edit", [:edit, post] %>
	<%= link_to "Delete", post_path(post), :confirm => "Are you sure?", :method => :delete %>
	<%= button_to "Delete", post, 
		:confirm => "Are you sure?", :method => :delete %>
	<hr />
</div>
<% end %>
<%= link_to "New Post", new_post_path %>

app/views/posts/new.html.erb
<h1>Create a new post</h1>
<%= render "form" %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<div class="entry">
	<%= @post.body %>
</div>

<h2>Comments</h2>

<% @post.comments.each do |comment| %>
	<p>By: <%= comment.author %></p>
	<div class="comment">
		<%= comment.body %>
	</div>
	<p>
		<%= button_to "Delete", [@post, comment],
			:confirm => "Are you sure?", :method => :delete %>
	</p>
<% end %>

<%= form_for [@post, Comment.new] do |form| %>
	<%= form.label :author, "Name" %>
	<%= form.text_field :author %>
	
	<%= form.text_area :body %>
	<%= form.submit %>
<% end %>

<%= link_to "Back", posts_path %>